on:
  workflow_dispatch:

jobs:
  get-versions-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: versions-diff
        run: echo "::set-output name=matrix::$(./check_updates.py | jq -R -s -c 'split("\n")[:-1]')"
    outputs:
      matrix: ${{ steps.versions-diff.outputs.matrix }}
  
  list-versions:
    runs-on: ubuntu-latest
    needs: get-versions-diff
    strategy:
      matrix:
        versions: ${{ fromJson(needs.get-versions-diff.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: list-versions
        run: echo "${{ matrix.versions }}"
