on:
  workflow_dispatch:

jobs:
  get-versions-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: versions-diff
        run: |
          pip install -r requirements.txt
          echo "::set-output name=matrix::$(./check_updates.py | jq -R -s -c 'split("\n")[:-1]')"
    outputs:
      matrix: ${{ steps.versions-diff.outputs.matrix }}
  
  create-branch:
    runs-on: ubuntu-latest
    needs: get-versions-diff
    strategy:
      matrix:
        versions: ${{ fromJson(needs.get-versions-diff.outputs.matrix) }}
    steps:
      - uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ matrix.versions }}/stable
          sha: '${{ github.event.pull_request.head.sha }}'
  
  open-issue:
    runs-on: ubuntu-latest
    needs: 
      - create-branch
      - get-versions-diff
    permissions:
      contents: read
      issues: write 
    strategy:
      matrix:
        versions: ${{ fromJson(needs.get-versions-diff.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: ${{ matrix.versions }}
